config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reports do
    resources :occurrences
  end

  resources :occurrences, only: :destroy
  resources :tasks

  root to: 'reports#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/occurrence.rb
class Occurrence < ApplicationRecord
  belongs_to :task

  validates_presence_of :started_at
  validates :duration, # a positive integer
    presence: true,
    numericality: {
      only_integer: true,
      greater_than: 0
    }

  def self.within_range(range_start, range_end)
    where('started_at >= :range_start and started_at < :range_end ', range_start: range_start, range_end: range_end)
  end

  def self.within_range_with_task(task, range_start, range_end)
    within_range(range_start, range_end).where(task: task)
  end

end

app/models/report.rb
class Report < ApplicationRecord
  validates :started_at, presence: true, uniqueness: true

  def duration_human
    ChronicDuration.output(duration)
  end

  def duration_human=(value)
    self.duration = ChronicDuration.parse(value)
  end

  def ended_at
    started_at + duration
  end

  def occurrences
    Occurrence.within_range(started_at, ended_at)
  end

  def occurrence_duration_human
    ChronicDuration.output(occurrence_duration)
  end

  def occurrence_duration_human=(value)
    self.occurrence_duration = ChronicDuration.parse(value)
  end

  def merged_occurrences(task)
    # merge a hash of possible occurrences and actual occurrences, keyed on started_at
    occurrences_within_range_with_task = occurrences.where(task: task).index_by(&:started_at)
    possible_occurrences = possible_occurrences(task).index_by(&:started_at)
    possible_occurrences.merge(occurrences_within_range_with_task)
  end

  def possible_occurrences(task)
    # logger.debug("po.task: #{task}")
    task = case task
    when String
      Task.find_or_initialize_by(name: task)
    when Task
      task
    else
      fail ArgumentError.new("Unsupported task type (#{task}).")
    end # rubocop:disable

    # @possible_occurrences ||= begin
      stepper = started_at
      end_time = started_at + self.duration
      possibilites = []
      while stepper < end_time
        occurrence = task.occurrences.build(started_at: stepper, duration: occurrence_duration)
        possibilites << occurrence
        stepper += occurrence_duration
      end
      possibilites
    # end
  end

  def tasks
    occurrences.collect(&:task).uniq.sort_by(&:name)
  end

  def self.with_start_time(start_hour=9)
    start_of_work_day = Time.current.beginning_of_day.change({ hour: start_hour })
    Report.find_or_create_by!({
      started_at: start_of_work_day
    })
  end
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :occurrences, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/occurrences_controller.rb
class OccurrencesController < ApplicationController
  def create
    if occurrence_params[:task_id].present?
      @occurrence = Occurrence.create!(occurrence_params)
    else
      task = Task.where(task_params).first_or_create
      @occurrence = task.occurrences.create!(occurrence_params)
    end

    if @occurrence.save
      flash[:success] = "Saved"
    else
      flash[:error] = "Issue saving"
    end

    redirect_to edit_report_url(@report)
  end

  def destroy
    @occurrence = Occurrence.find(params[:id]).destroy
    report = @occurrence.report
    flash[:warning] = "Occurrence deleted successfully."
    redirect_to edit_report_url(report)
  end

  private

  def occurrence_params
    params.require(:occurrence).permit(:started_at, :task_id)
  end

  def task_params
    params.require(:task).permit(:name)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def destroy
    report = Report.find(params[:id]).destroy
    flash[:warning] = "Report deleted successfully (#{report.started_at}, id: #{report.id})."
    redirect_to reports_url(report)
  end

  def edit
    @report = Report.find(params[:id])
  end

  def index
    @reports = Report.all
  end

  def new
    @report = Report.with_start_time
    render :edit
  end

  def show
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(report_params)
      redirect_to reports_url
    else
      render 'edit'
    end
  end


  private

  def report_params
    params.require(:report).permit(:duration_human, :occurrence_duration_human)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_url
    else
      render 'new'
    end
  end

  def destroy
    task = Task.find(params[:id])
    if task.destroy
      flash[:success] = "Task ('#{task.name}', id:#{task.id}) was destroyed."
    else
      flash[:error] = "Issue destroying task (#{task.id}: #{task.name})."
    end
    redirect_to tasks_url
  end

  def edit
    @task = Task.find(params[:id])
  end

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_url
    else
      render 'edit'
    end
  end

  private

  def task_params
    params.require(:task).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav_bar.html.haml
/ see: http://foundation.zurb.com/sites/docs/top-bar.html
.top-bar
  .top-bar-left
    %ul.dropdown.menu{"data-dropdown-menu" => ""}
      %li.menu-text= link_to('ETT', root_path)
      %li
        = link_to('Reports', reports_path)
      %li
        = link_to('Tasks', tasks_path)
  -# .top-bar-right
    %ul.menu
      %li
        %input{:placeholder => "Search", :type => "search"}/
      %li
        %button.button{:type => "button"} Search

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")/

    %title= content_for?(:title) ? yield(:title) : "ETT"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    = render 'layouts/nav_bar'
    = display_flash_messages # see: foundation_rails_helper
    = yield

app/views/reports/_task_row.html.haml
%tr
  %td{title: task.name}
    - if task.new_record?
      = text_field_tag 'task[name]', task.name, id: 'new_task_name', placeholder: 'Task Name'
    - else
      = link_to task.name, edit_task_path(task), title: "Edit #{task.name}"

  - possible_occurrences.each do |started_at, possible_occurrence|
    %td
      - if possible_occurrence.new_record?
        = simple_form_for [report, possible_occurrence], wrapper: :inline_form  do |f|
          -# = debug(f.object)
          = hidden_field_tag 'task[name]', task.name
          = f.hidden_field :task_id
          = f.hidden_field :started_at
          = f.button :submit, 'O', class: 'round', title: 'Create'

      - else
        = button_to 'X', possible_occurrence, class: 'button round warning', method: :delete, title: 'Remove'

app/views/reports/edit.html.haml
%h1
  Tracking #{@report.started_at.to_formatted_s(:dow_with_long)}
  = link_to report_path(@report), title: 'Show' do
    %i.fi-page

-# Used for headers and new row
- new_task = Task.new(name: 'New Task')
- possible_occurrences = @report.merged_occurrences(new_task)
%section#tasks
  %table.table.hover{role: "grid"}
    %thead
      %th Task Name
      - possible_occurrences.each do |started_at, possible_occurrence|
        %th= possible_occurrence.started_at.strftime('%H:%M')
    %tbody
      - for task in @report.tasks
        = render partial: 'task_row', locals: { task: task, possible_occurrences: @report.merged_occurrences(task) }
      
      = render partial: 'task_row', locals: { report: @report, task: new_task, possible_occurrences: possible_occurrences }

%div
  = simple_form_for @report do |f|
    =f.input :duration_human
    =f.input :occurrence_duration_human
    =f.button :submit

app/views/reports/index.html.haml
%h1 Reports

%table#reports
  %thead
    %th Started At
    %th Actions
    %th Task Ct.
    %th Duration
    %th Occurrence Duration
    %th Memo
  %tbody
    - for report in @reports
      %tr
        %td
          = link_to(report.started_at.to_formatted_s(:dow_with_long), report_path(report))
        %td
          %a{href: edit_report_path(report), title: 'Edit'}
            %i.fi-pencil
          |
          = button_to 'X', report_path(report), class: 'button alert round tiny', method: 'delete', data: { confirm: 'Are you sure?', disable_with: 'loading...' }, title: 'Delete'
        %td= report.tasks.size
        %td= report.duration_human
        %td= report.occurrence_duration_human
        %td= report.memo

app/views/reports/show.html.haml
%h1
  Tracking #{@report.started_at.to_formatted_s(:dow_with_long)}
  = link_to edit_report_path(@report), title: 'Edit' do
    %i.fi-page-edit

%section#tasks
  %table
    %thead
      %th Task Name
      - @report.merged_occurrences('header').each do |started_at, possible_occurrence|
        %th= possible_occurrence.started_at.strftime('%H:%M')
    %tbody
      - for task in @report.tasks
        %tr
          %td
            = task.name

          - @report.merged_occurrences(task).each do |started_at, possible_occurrence|
            %td
              - if possible_occurrence.new_record?
                O
              - else
                %i.fi-x-circle

%div.right
  %span Duration: #{ChronicDuration.output(@report.duration)}
  %span Occurrence Duration: #{ChronicDuration.output(@report.occurrence_duration)}

app/views/tasks/_form.html.haml
= simple_form_for(@task) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %thead
    %tr
      %th Name
      %th Occurrence ct
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.occurrences.count
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p Name: #{@task.name}

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path